# Generated by Django 5.2.14 on 2026-05-21 08:58

import django.db.models.deletion
import underground_crm.fields
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "cache_ttl_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override the automatically calculated cache duration in seconds. Setting this to 0 will disable caching entirely. Leave blank to use the calculated value.",
                        null=True,
                        verbose_name="Cache TTL override (seconds)",
                    ),
                ),
                ("legacy_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("html", 1), ("image", 5), ("blockquote", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "blockquote",
                                        "image",
                                    ],
                                    "label": "Rich Text",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "help_text": "Paste raw HTML directly. Useful for migrating existing content or embedding custom markup.",
                                    "label": "Raw HTML",
                                },
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full-width", "Full width"),
                                        ("left", "Left aligned"),
                                        ("right", "Right aligned"),
                                        ("w-50", "Half width"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("caption", 3), ("alignment", 4)]],
                                {
                                    "icon": "image",
                                    "label": "Image",
                                    "template": "underground_crm/blocks/image_block.html",
                                },
                            ),
                            6: ("wagtail.blocks.BlockQuoteBlock", (), {"label": "Blockquote"}),
                        },
                    ),
                ),
                (
                    "search_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Search image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="UndergroundBasicPage",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                (
                    "show_toc",
                    models.BooleanField(
                        default=False,
                        help_text="Show the table-of-contents sidebar for this page.",
                        verbose_name="Show table of contents",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Page",
            },
            bases=("underground_crm.basicpage",),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                (
                    "page_size",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of posts to display per page."
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
            },
            bases=("underground_crm.basicpage",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="This is updated automatically. It is only defined as a field so we can migrate legacy events seamlessly.",
                        null=True,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="underground_crm.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("underground_crm.basicpage",),
        ),
        migrations.CreateModel(
            name="EventGuest",
            fields=[
                (
                    "id",
                    underground_crm.fields.UUIDAutoField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accompanying_population",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="underground_crm.eventpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "undergroundbasicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.undergroundbasicpage",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("underground_crm.undergroundbasicpage",),
        ),
    ]
