# Generated by Django 5.2.14 on 2026-05-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0028_person_nullable_fields"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicpage",
            name="cache_ttl_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override the automatically calculated cache duration in seconds. Setting this to 0 will disable caching entirely. Leave blank to use the calculated value.",
                null=True,
                verbose_name="Cache TTL override (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="basicpage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="basicpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="population",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="This is updated automatically. It is only defined as a field so we can migrate legacy events seamlessly.",
                null=True,
            ),
        ),
    ]
