# Generated by Django 5.2.14 on 2026-05-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "underground_crm",
            "0029_basicpage_cache_ttl_override_alter_basicpage_author_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicpage",
            name="og_type",
        ),
    ]
