repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: .venv/bin/pylint
        language: system
        types: [python]
        args:
          - --load-plugins=pylint_django
          - --django-settings-module=underground_crm.settings
          - --errors-only
