# Generated by Django 5.2.13 on 2026-05-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0001_initial"),
        ("underground_email", "0008_add_preview_text_to_emailcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="unsubscription_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Which tag should be removed if the recipient clicks to unsubscribe? If not set, such recipients will be converted to tombstones (losing their membership).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="underground_crm.tag",
                verbose_name="Unsubscription tag",
            ),
        ),
    ]
