# Generated by Django 5.2.14 on 2026-05-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("underground_crm", "0002_pages"),
        ("underground_email", "0011_alter_emailcampaign_body_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPage",
            fields=[
                (
                    "basicpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="underground_crm.basicpage",
                    ),
                ),
                (
                    "allow_monthly_payments",
                    models.BooleanField(default=True, verbose_name="Allow monthly payments"),
                ),
                (
                    "allow_annual_payments",
                    models.BooleanField(default=True, verbose_name="Allow annual payments"),
                ),
                (
                    "email_every_time",
                    models.BooleanField(
                        default=False,
                        help_text="Send the success email for every donation. When off, only the first donation to this page triggers an email.",
                        verbose_name="Email every time",
                    ),
                ),
                (
                    "donor_tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tag applied to the donor's person record after a successful payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="underground_crm.tag",
                        verbose_name="Donor tag",
                    ),
                ),
                (
                    "redirect_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page to redirect to after a successful payment. Leave blank to show a thank-you message on this page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Redirect to",
                    ),
                ),
                (
                    "success_email",
                    models.ForeignKey(
                        blank=True,
                        help_text="Email campaign sent to the donor after a successful payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="underground_email.emailcampaign",
                        verbose_name="Success email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Page",
            },
            bases=("underground_crm.basicpage",),
        ),
    ]
