# Generated by Django 5.2.14 on 2026-05-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underground_crm", "0029_basicpage_cache_ttl_override_alter_basicpage_author_and_more"),
        ("underground_email", "0011_alter_emailcampaign_body_and_more"),
        ("underground_payments", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentpage",
            name="donor_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="Tag applied to the donor after a successful payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="underground_crm.tag",
                verbose_name="Donor tag",
            ),
        ),
        migrations.AlterField(
            model_name="paymentpage",
            name="email_every_time",
            field=models.BooleanField(
                default=False,
                help_text="Send the success email for every donation. If set to false, only the donor's first donation at this page will trigger an email.",
                verbose_name="Email every time?",
            ),
        ),
        migrations.AlterField(
            model_name="paymentpage",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The redirection page after a successful payment. Leave blank to show a thank-you message on this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Redirect to",
            ),
        ),
        migrations.AlterField(
            model_name="paymentpage",
            name="success_email",
            field=models.ForeignKey(
                blank=True,
                help_text="Email sent to the donor after a successful payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="underground_email.emailcampaign",
                verbose_name="Success email",
            ),
        ),
    ]
